Lidar_front_end:
   lidar_type: 4 # 1 for Livox-avia, 3 for Ouster-OS1-64, 4 for Intel-Realsense-L515
   N_SCANS: 6 # used only if lidar_type is Livox-avia
   using_raw_point: 1
   point_step: 5
   # group_size: 1
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 0            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.02        # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]
   track_windows_size: 7           # The tracking window size for image tracking & optical flow
   # esikf_iter_times: 2

r3live_vio:
   image_width: 640
   image_height: 480
   camera_intrinsic:
      [456.94921875, 0.0, 319.19140625,
      0.0, 456.87890625, 252.0625,
      0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [0,0,0,0,0]  #k1, k2, p1, p2, k3   
   #imu-camera extrinsics, better calibration required
   camera_ext_t: [0.0005699999746866524, 0.012450000271201134, -0.016419999301433563]
   camera_ext_R:
      [0, 0, 1,
       -1, 0, 0,
       0, -1, 0]
   
r3live_lio:        
   fov_degree: 75 # Default value: 360
   lio_update_point_step: 1   # Point step used for LIO update.  
   max_iteration: 10      # Maximum times of LIO esikf.
   long_rang_pt_dis: 100
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.30   
   filter_size_surf: 0.001
   filter_size_surf_z: 0.001
   filter_size_map: 0.05
   voxel_downsample_size_surf: 0.1
   voxel_downsample_size_axis_z: 0.1
   # lidar_ext_t: [0.05512, 0.02226, 0.0297]; # Horizon
   # lidar_ext_t: [0.04165, 0.02326, -0.0284]; # Avia
   lidar_ext_t: [0.0005699999746866524, 0.012450000271201134, -0.016419999301433563] # L515
   lidar_undistort: 0